<?xml version="1.0" ?>
<gml:FeatureCollection xmlns:cimlk="http://cimlk.nl/1.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ns1="http://www.w3.org/1999/xhtml" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cimlk.nl/1.0 file:/C:/Users/dgree/OneDrive/Documenten/GitHub/CIMLK/hale/imlk.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/deprecatedTypes.xsd">
  <gml:featureMember>
    <cimlk:Maatregel gml:id="NL.imlk.M_09214908_750">
      <cimlk:identificatie>
        <cimlk:NEN3610ID>
          <cimlk:namespace>NL.imlk</cimlk:namespace>
          <cimlk:lokaalID>M_09214908_750</cimlk:lokaalID>
        </cimlk:NEN3610ID>
      </cimlk:identificatie>
      <cimlk:naam>Milieuzone Arnhem</cimlk:naam>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.9441816174000002</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.9039797614</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>PM2,5</cimlk:stof>
          <cimlk:schalingsfactor>0.5267647361000001</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>PM2,5</cimlk:stof>
          <cimlk:schalingsfactor>0.6059097507</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>PM2,5</cimlk:stof>
          <cimlk:schalingsfactor>0.8174357943</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>PM2,5</cimlk:stof>
          <cimlk:schalingsfactor>0.6821957853999999</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>PM2,5</cimlk:stof>
          <cimlk:schalingsfactor>0.8489130209</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>PM2,5</cimlk:stof>
          <cimlk:schalingsfactor>0.7855182547999998</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.9141725043</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.8950386321000001</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.9400425053</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.8774656717</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.9164222179</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.9207776172000002</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.9331290626000002</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.9082675547999999</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.7748446275000002</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.7563255147</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.8757882688</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.7720705438</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.8812743722</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>z</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.8591397373000002</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.7667369944</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>m</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.8444599920000001</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:tijdstipRegistratie>2022-02-08T07:08:00Z</cimlk:tijdstipRegistratie>
      <cimlk:geometrie>
        <gml:Polygon srsName="EPSG:28992" srsDimension="2">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>190311.357749574 443530.577094441 191193.50649225 443029.898078328 191193.50649225 443029.898078328 191396.162284486 443310.039908772 191431.925071351 443643.825919514 191324.636710755 444174.307258015 190817.997230165 444216.030509358 190460.369361512 444114.70261324 190132.543815248 443673.628241902 190311.357749574 443530.577094441</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>
      </cimlk:geometrie>
    </cimlk:Maatregel>
  </gml:featureMember>
  <gml:featureMember>
    <cimlk:Maatregel gml:id="NL.imlk.M_09214908_751">
      <cimlk:identificatie>
        <cimlk:NEN3610ID>
          <cimlk:namespace>NL.imlk</cimlk:namespace>
          <cimlk:lokaalID>M_09214908_751</cimlk:lokaalID>
        </cimlk:NEN3610ID>
      </cimlk:identificatie>
      <cimlk:naam>Schone bussen Arnhem</cimlk:naam>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.26</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>b</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.26</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.26</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>NOx</cimlk:stof>
          <cimlk:schalingsfactor>0.26</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.14</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>b</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.14</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.14</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>NO2</cimlk:stof>
          <cimlk:schalingsfactor>0.14</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>c</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.36</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>b</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.36</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>e</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.36</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:maatregelen>
        <cimlk:Maatregelfactor>
          <cimlk:voertuigtype>b</cimlk:voertuigtype>
          <cimlk:wegsoort>d</cimlk:wegsoort>
          <cimlk:stof>PM10</cimlk:stof>
          <cimlk:schalingsfactor>0.36</cimlk:schalingsfactor>
        </cimlk:Maatregelfactor>
      </cimlk:maatregelen>
      <cimlk:tijdstipRegistratie>2022-02-08T07:08:00Z</cimlk:tijdstipRegistratie>
      <cimlk:geometrie>
        <gml:Polygon srsName="EPSG:28992" srsDimension="2">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>191293.423760613 447351.963964171 188938.289588528 445503.073586085 187221.462808877 439912.38125235 190060.830175223 439252.063260177 191051.307163483 441563.176232784 192922.208141308 442069.420026783 194639.034920959 443962.331604347 193076.282339482 446581.592973302 193076.282339482 446581.592973302 191293.423760613 447351.963964171</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>
      </cimlk:geometrie>
    </cimlk:Maatregel>
  </gml:featureMember>
</gml:FeatureCollection>
